#### 1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно


In [2]:
import numpy as np
import pandas as pd
import matplotlib as plt

In [3]:
a=np.arange(12,24)
print(a)

[12 13 14 15 16 17 18 19 20 21 22 23]


#### 2. Cоздать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.


In [4]:
a1=np.reshape(a,(3,4))
a2=np.reshape(a,(6,2))
a3=np.reshape(a,(4,3))
a4=np.reshape(a,(2,6))
a5=np.reshape(a,(12,1))
print(a1,a2,a3,a4,a5)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] [[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]] [[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]] [[12 13 14 15 16 17]
 [18 19 20 21 22 23]] [[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


#### 3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).


In [5]:
a1=a.reshape(2, -1)
a2=a.reshape(3, -1)
a3=a.reshape(-1, 2)
a4=a.reshape(-1, 3)
a5=a.reshape(12, -1)
print(a1)
print(a2)
print(a3)
print(a4)
print(a5)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


#### 4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?


In [6]:
x=np.arange(12, 24)
matr=x.reshape(3,4)
y=matr.reshape(12,1)
print(x)
print(y)

[12 13 14 15 16 17 18 19 20 21 22 23]
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


In [8]:
# массив Numpy, состоящий из одного столбца и 12 строк, нельзя назвать одномерным.

#### 5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [9]:
c=np.random.randn(3,4)
c


array([[ 1.29449408, -0.58347352, -1.35178187,  0.11781296],
       [-0.69122639, -0.98472884, -0.59591991,  0.81105744],
       [-0.38597233, -0.17797091,  0.30879285,  0.3562687 ]])

In [10]:
print(c.size)
c=c.flatten()
print(c.size)
c

12
12


array([ 1.29449408, -0.58347352, -1.35178187,  0.11781296, -0.69122639,
       -0.98472884, -0.59591991,  0.81105744, -0.38597233, -0.17797091,
        0.30879285,  0.3562687 ])

#### 6.Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [11]:
a=np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

##### 7.Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [12]:
b=np.arange(20, 1, -2).reshape(1,10)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [13]:
#  a - одномерный, а b - двумерный

##### 8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.


In [14]:
a = np.zeros((2, 2))
a

array([[0., 0.],
       [0., 0.]])

In [15]:
b = np.zeros((3, 2))+1
b


array([[1., 1.],
       [1., 1.],
       [1., 1.]])

v = np.vstack((a, b))
v

In [17]:
a.shape, b.shape, v.shape

((2, 2), (3, 2), (5, 2))

In [18]:
v.size

10

##### 9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?


In [19]:
a=np.arange(0, 12)
a


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [20]:
A=a.reshape(4,3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [21]:
At=A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [22]:
B = np.dot(A, At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [23]:
B.shape

(4, 4)

In [24]:
B_inv=np.linalg.inv(B)
B_inv

LinAlgError: Singular matrix

In [25]:
#Вычислить обратную матрицу для матрицы B не получится, т.к. это вырожденная (сингулярная)

#### 10. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [26]:
np.random.seed(42)

##### 11. Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [27]:
c=np.random.randint(0, 16,16)
c

array([ 6,  3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4])

#### 12. Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.


In [28]:
C=c.reshape(4,4)
C

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

In [29]:
D=B+C*10
D


array([[ 65,  44, 143, 172],
       [114, 120, 206, 162],
       [ 83, 176, 169, 272],
       [132, 222, 282, 342]])

In [30]:
d=np.linalg.det(D)
d

-28511999.999999944

In [31]:
r=np.linalg.matrix_rank(D)
r

4

In [32]:
D_inv=np.linalg.inv(D)
D_inv

array([[ 0.00935396,  0.04486532,  0.05897517, -0.07286055],
       [-0.01503577, -0.00122896, -0.00192971,  0.00967873],
       [-0.00356692, -0.01782828, -0.04152146,  0.04326178],
       [ 0.00909091, -0.00181818,  0.01272727, -0.01090909]])

#### 13. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [33]:
D_inv=np.where(D_inv<0, 0,1)
D_inv

array([[1, 1, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [1, 0, 1, 0]])

In [34]:
print(B)
print(C)
E=np.where(D_inv==1, B, C)
E

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
[[ 6  3 12 14]
 [10  7 12  4]
 [ 6  9  2  6]
 [10 10  7  4]]


array([[  5,  14,  23,  14],
       [ 10,   7,  12, 122],
       [  6,   9,   2, 212],
       [ 32,  10, 212,   4]])